// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analyses.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const countResultsForProfileAnalyte = `-- name: CountResultsForProfileAnalyte :one
SELECT count(*) FROM lab_results
WHERE profile_id = $1 AND analyte_id = $2
`

type CountResultsForProfileAnalyteParams struct {
	ProfileID uuid.UUID `json:"profile_id"`
	AnalyteID uuid.UUID `json:"analyte_id"`
}

func (q *Queries) CountResultsForProfileAnalyte(ctx context.Context, arg CountResultsForProfileAnalyteParams) (int64, error) {
	row := q.db.QueryRow(ctx, countResultsForProfileAnalyte, arg.ProfileID, arg.AnalyteID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAnalysis = `-- name: GetAnalysis :one
SELECT profile_id, analyte_id, content, result_count, generated_at FROM analyte_analyses
WHERE profile_id = $1 AND analyte_id = $2
`

type GetAnalysisParams struct {
	ProfileID uuid.UUID `json:"profile_id"`
	AnalyteID uuid.UUID `json:"analyte_id"`
}

func (q *Queries) GetAnalysis(ctx context.Context, arg GetAnalysisParams) (AnalyteAnalysis, error) {
	row := q.db.QueryRow(ctx, getAnalysis, arg.ProfileID, arg.AnalyteID)
	var i AnalyteAnalysis
	err := row.Scan(
		&i.ProfileID,
		&i.AnalyteID,
		&i.Content,
		&i.ResultCount,
		&i.GeneratedAt,
	)
	return i, err
}

const upsertAnalysis = `-- name: UpsertAnalysis :exec
INSERT INTO analyte_analyses (profile_id, analyte_id, content, result_count, generated_at)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT (profile_id, analyte_id) DO UPDATE
SET content = EXCLUDED.content,
    result_count = EXCLUDED.result_count,
    generated_at = now()
`

type UpsertAnalysisParams struct {
	ProfileID   uuid.UUID `json:"profile_id"`
	AnalyteID   uuid.UUID `json:"analyte_id"`
	Content     string    `json:"content"`
	ResultCount int32     `json:"result_count"`
}

func (q *Queries) UpsertAnalysis(ctx context.Context, arg UpsertAnalysisParams) error {
	_, err := q.db.Exec(ctx, upsertAnalysis,
		arg.ProfileID,
		arg.AnalyteID,
		arg.Content,
		arg.ResultCount,
	)
	return err
}
