// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analytes.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addAnalyteNamesAsAliases = `-- name: AddAnalyteNamesAsAliases :exec
INSERT INTO analyte_aliases (analyte_id, raw_name)
SELECT $1, name FROM analytes WHERE id = ANY($2::uuid[])
ON CONFLICT (raw_name) DO NOTHING
`

type AddAnalyteNamesAsAliasesParams struct {
	Target  uuid.UUID   `json:"target"`
	Sources []uuid.UUID `json:"sources"`
}

// Keep the merged-away names as aliases so future uploads map to the target.
func (q *Queries) AddAnalyteNamesAsAliases(ctx context.Context, arg AddAnalyteNamesAsAliasesParams) error {
	_, err := q.db.Exec(ctx, addAnalyteNamesAsAliases, arg.Target, arg.Sources)
	return err
}

const countResultsForAnalyte = `-- name: CountResultsForAnalyte :one
SELECT count(*) FROM lab_results WHERE analyte_id = $1
`

func (q *Queries) CountResultsForAnalyte(ctx context.Context, analyteID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countResultsForAnalyte, analyteID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAnalyte = `-- name: CreateAnalyte :one
INSERT INTO analytes (name, default_unit, category)
VALUES ($1, $2, $3)
RETURNING id, name, default_unit, loinc, category, created_at, specimens
`

type CreateAnalyteParams struct {
	Name        string      `json:"name"`
	DefaultUnit pgtype.Text `json:"default_unit"`
	Category    pgtype.Text `json:"category"`
}

func (q *Queries) CreateAnalyte(ctx context.Context, arg CreateAnalyteParams) (Analyte, error) {
	row := q.db.QueryRow(ctx, createAnalyte, arg.Name, arg.DefaultUnit, arg.Category)
	var i Analyte
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DefaultUnit,
		&i.Loinc,
		&i.Category,
		&i.CreatedAt,
		&i.Specimens,
	)
	return i, err
}

const deleteAnalytes = `-- name: DeleteAnalytes :exec
DELETE FROM analytes WHERE id = ANY($1::uuid[])
`

// Sources must no longer be referenced by lab_results (RESTRICT); aliases were
// repointed, and remaining favorites/analyses for the sources cascade away here.
func (q *Queries) DeleteAnalytes(ctx context.Context, sources []uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAnalytes, sources)
	return err
}

const getAliasByRawName = `-- name: GetAliasByRawName :one
SELECT a.id, a.name, a.default_unit, a.loinc, a.category, a.created_at, a.specimens FROM analytes a
JOIN analyte_aliases al ON al.analyte_id = a.id
WHERE lower(btrim(al.raw_name)) = lower(btrim($1))
LIMIT 1
`

func (q *Queries) GetAliasByRawName(ctx context.Context, btrim string) (Analyte, error) {
	row := q.db.QueryRow(ctx, getAliasByRawName, btrim)
	var i Analyte
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DefaultUnit,
		&i.Loinc,
		&i.Category,
		&i.CreatedAt,
		&i.Specimens,
	)
	return i, err
}

const getAnalyte = `-- name: GetAnalyte :one
SELECT id, name, default_unit, loinc, category, created_at, specimens FROM analytes
WHERE id = $1
`

func (q *Queries) GetAnalyte(ctx context.Context, id uuid.UUID) (Analyte, error) {
	row := q.db.QueryRow(ctx, getAnalyte, id)
	var i Analyte
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DefaultUnit,
		&i.Loinc,
		&i.Category,
		&i.CreatedAt,
		&i.Specimens,
	)
	return i, err
}

const getAnalyteByName = `-- name: GetAnalyteByName :one
SELECT id, name, default_unit, loinc, category, created_at, specimens FROM analytes
WHERE lower(btrim(name)) = lower(btrim($1))
LIMIT 1
`

func (q *Queries) GetAnalyteByName(ctx context.Context, btrim string) (Analyte, error) {
	row := q.db.QueryRow(ctx, getAnalyteByName, btrim)
	var i Analyte
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DefaultUnit,
		&i.Loinc,
		&i.Category,
		&i.CreatedAt,
		&i.Specimens,
	)
	return i, err
}

const ignoreAnalytePair = `-- name: IgnoreAnalytePair :exec
INSERT INTO ignored_analyte_pairs (analyte_a, analyte_b)
VALUES (LEAST($1::uuid, $2::uuid), GREATEST($1::uuid, $2::uuid))
ON CONFLICT DO NOTHING
`

type IgnoreAnalytePairParams struct {
	A uuid.UUID `json:"a"`
	B uuid.UUID `json:"b"`
}

func (q *Queries) IgnoreAnalytePair(ctx context.Context, arg IgnoreAnalytePairParams) error {
	_, err := q.db.Exec(ctx, ignoreAnalytePair, arg.A, arg.B)
	return err
}

const listAnalytes = `-- name: ListAnalytes :many
SELECT id, name, default_unit, loinc, category, created_at, specimens FROM analytes
ORDER BY category NULLS LAST, name
`

func (q *Queries) ListAnalytes(ctx context.Context) ([]Analyte, error) {
	rows, err := q.db.Query(ctx, listAnalytes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Analyte{}
	for rows.Next() {
		var i Analyte
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DefaultUnit,
			&i.Loinc,
			&i.Category,
			&i.CreatedAt,
			&i.Specimens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnalytesWithDataForProfile = `-- name: ListAnalytesWithDataForProfile :many
SELECT DISTINCT a.id, a.name, a.default_unit, a.loinc, a.category, a.created_at, a.specimens FROM analytes a
JOIN lab_results r ON r.analyte_id = a.id
WHERE r.profile_id = $1
ORDER BY a.category NULLS LAST, a.name
`

func (q *Queries) ListAnalytesWithDataForProfile(ctx context.Context, profileID uuid.UUID) ([]Analyte, error) {
	rows, err := q.db.Query(ctx, listAnalytesWithDataForProfile, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Analyte{}
	for rows.Next() {
		var i Analyte
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DefaultUnit,
			&i.Loinc,
			&i.Category,
			&i.CreatedAt,
			&i.Specimens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIgnoredAnalytePairs = `-- name: ListIgnoredAnalytePairs :many
SELECT analyte_a, analyte_b FROM ignored_analyte_pairs
`

type ListIgnoredAnalytePairsRow struct {
	AnalyteA uuid.UUID `json:"analyte_a"`
	AnalyteB uuid.UUID `json:"analyte_b"`
}

func (q *Queries) ListIgnoredAnalytePairs(ctx context.Context) ([]ListIgnoredAnalytePairsRow, error) {
	rows, err := q.db.Query(ctx, listIgnoredAnalytePairs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIgnoredAnalytePairsRow{}
	for rows.Next() {
		var i ListIgnoredAnalytePairsRow
		if err := rows.Scan(&i.AnalyteA, &i.AnalyteB); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const matchAliasBySpecimen = `-- name: MatchAliasBySpecimen :one
SELECT a.id, a.name, a.default_unit, a.loinc, a.category, a.created_at, a.specimens FROM analytes a
JOIN analyte_aliases al ON al.analyte_id = a.id
WHERE lower(btrim(al.raw_name)) = lower(btrim($1))
  AND (
    ($2::bool AND 'urine' = ANY(COALESCE(a.specimens, '{}')))
    OR (NOT $2::bool AND NOT ('urine' = ANY(COALESCE(a.specimens, '{}'))))
  )
LIMIT 1
`

type MatchAliasBySpecimenParams struct {
	RawName   string `json:"raw_name"`
	WantUrine bool   `json:"want_urine"`
}

func (q *Queries) MatchAliasBySpecimen(ctx context.Context, arg MatchAliasBySpecimenParams) (Analyte, error) {
	row := q.db.QueryRow(ctx, matchAliasBySpecimen, arg.RawName, arg.WantUrine)
	var i Analyte
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DefaultUnit,
		&i.Loinc,
		&i.Category,
		&i.CreatedAt,
		&i.Specimens,
	)
	return i, err
}

const matchAnalyteBySpecimen = `-- name: MatchAnalyteBySpecimen :one
SELECT id, name, default_unit, loinc, category, created_at, specimens FROM analytes
WHERE lower(btrim(name)) = lower(btrim($1))
  AND (
    ($2::bool AND 'urine' = ANY(COALESCE(specimens, '{}')))
    OR (NOT $2::bool AND NOT ('urine' = ANY(COALESCE(specimens, '{}'))))
  )
LIMIT 1
`

type MatchAnalyteBySpecimenParams struct {
	Name      string `json:"name"`
	WantUrine bool   `json:"want_urine"`
}

func (q *Queries) MatchAnalyteBySpecimen(ctx context.Context, arg MatchAnalyteBySpecimenParams) (Analyte, error) {
	row := q.db.QueryRow(ctx, matchAnalyteBySpecimen, arg.Name, arg.WantUrine)
	var i Analyte
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DefaultUnit,
		&i.Loinc,
		&i.Category,
		&i.CreatedAt,
		&i.Specimens,
	)
	return i, err
}

const migrateFavoritesToAnalyte = `-- name: MigrateFavoritesToAnalyte :exec
INSERT INTO favorites (profile_id, analyte_id)
SELECT profile_id, $1 FROM favorites WHERE analyte_id = ANY($2::uuid[])
ON CONFLICT DO NOTHING
`

type MigrateFavoritesToAnalyteParams struct {
	Target  uuid.UUID   `json:"target"`
	Sources []uuid.UUID `json:"sources"`
}

func (q *Queries) MigrateFavoritesToAnalyte(ctx context.Context, arg MigrateFavoritesToAnalyteParams) error {
	_, err := q.db.Exec(ctx, migrateFavoritesToAnalyte, arg.Target, arg.Sources)
	return err
}

const repointAliasesToAnalyte = `-- name: RepointAliasesToAnalyte :exec
UPDATE analyte_aliases SET analyte_id = $1
WHERE analyte_id = ANY($2::uuid[])
`

type RepointAliasesToAnalyteParams struct {
	Target  uuid.UUID   `json:"target"`
	Sources []uuid.UUID `json:"sources"`
}

func (q *Queries) RepointAliasesToAnalyte(ctx context.Context, arg RepointAliasesToAnalyteParams) error {
	_, err := q.db.Exec(ctx, repointAliasesToAnalyte, arg.Target, arg.Sources)
	return err
}

const repointResultsToAnalyte = `-- name: RepointResultsToAnalyte :exec

UPDATE lab_results SET analyte_id = $1
WHERE analyte_id = ANY($2::uuid[])
`

type RepointResultsToAnalyteParams struct {
	Target  uuid.UUID   `json:"target"`
	Sources []uuid.UUID `json:"sources"`
}

// Merge steps: fold one or more source analytes into a target. Run in order,
// inside a transaction (see mergeAnalytes).
func (q *Queries) RepointResultsToAnalyte(ctx context.Context, arg RepointResultsToAnalyteParams) error {
	_, err := q.db.Exec(ctx, repointResultsToAnalyte, arg.Target, arg.Sources)
	return err
}

const unignoreAnalytePair = `-- name: UnignoreAnalytePair :exec
DELETE FROM ignored_analyte_pairs
WHERE analyte_a = LEAST($1::uuid, $2::uuid)
  AND analyte_b = GREATEST($1::uuid, $2::uuid)
`

type UnignoreAnalytePairParams struct {
	A uuid.UUID `json:"a"`
	B uuid.UUID `json:"b"`
}

func (q *Queries) UnignoreAnalytePair(ctx context.Context, arg UnignoreAnalytePairParams) error {
	_, err := q.db.Exec(ctx, unignoreAnalytePair, arg.A, arg.B)
	return err
}

const upsertAlias = `-- name: UpsertAlias :exec
INSERT INTO analyte_aliases (analyte_id, raw_name)
VALUES ($1, $2)
ON CONFLICT (raw_name) DO NOTHING
`

type UpsertAliasParams struct {
	AnalyteID uuid.UUID `json:"analyte_id"`
	RawName   string    `json:"raw_name"`
}

func (q *Queries) UpsertAlias(ctx context.Context, arg UpsertAliasParams) error {
	_, err := q.db.Exec(ctx, upsertAlias, arg.AnalyteID, arg.RawName)
	return err
}
