// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analyses.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getAnalysis = `-- name: GetAnalysis :one
SELECT profile_id, analyte_id, content, result_count, generated_at FROM analyte_analyses
WHERE profile_id = $1 AND analyte_id = $2
`

type GetAnalysisParams struct {
	ProfileID uuid.UUID `json:"profile_id"`
	AnalyteID uuid.UUID `json:"analyte_id"`
}

func (q *Queries) GetAnalysis(ctx context.Context, arg GetAnalysisParams) (AnalyteAnalysis, error) {
	row := q.db.QueryRow(ctx, getAnalysis, arg.ProfileID, arg.AnalyteID)
	var i AnalyteAnalysis
	err := row.Scan(
		&i.ProfileID,
		&i.AnalyteID,
		&i.Content,
		&i.ResultCount,
		&i.GeneratedAt,
	)
	return i, err
}

const resultStatsForProfileAnalyte = `-- name: ResultStatsForProfileAnalyte :one
SELECT count(*)::int AS count,
       COALESCE(max(updated_at), to_timestamp(0))::timestamptz AS last_changed
FROM lab_results
WHERE profile_id = $1 AND analyte_id = $2
`

type ResultStatsForProfileAnalyteParams struct {
	ProfileID uuid.UUID `json:"profile_id"`
	AnalyteID uuid.UUID `json:"analyte_id"`
}

type ResultStatsForProfileAnalyteRow struct {
	Count       int32              `json:"count"`
	LastChanged pgtype.Timestamptz `json:"last_changed"`
}

func (q *Queries) ResultStatsForProfileAnalyte(ctx context.Context, arg ResultStatsForProfileAnalyteParams) (ResultStatsForProfileAnalyteRow, error) {
	row := q.db.QueryRow(ctx, resultStatsForProfileAnalyte, arg.ProfileID, arg.AnalyteID)
	var i ResultStatsForProfileAnalyteRow
	err := row.Scan(&i.Count, &i.LastChanged)
	return i, err
}

const upsertAnalysis = `-- name: UpsertAnalysis :exec
INSERT INTO analyte_analyses (profile_id, analyte_id, content, result_count, generated_at)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT (profile_id, analyte_id) DO UPDATE
SET content = EXCLUDED.content,
    result_count = EXCLUDED.result_count,
    generated_at = now()
`

type UpsertAnalysisParams struct {
	ProfileID   uuid.UUID `json:"profile_id"`
	AnalyteID   uuid.UUID `json:"analyte_id"`
	Content     string    `json:"content"`
	ResultCount int32     `json:"result_count"`
}

func (q *Queries) UpsertAnalysis(ctx context.Context, arg UpsertAnalysisParams) error {
	_, err := q.db.Exec(ctx, upsertAnalysis,
		arg.ProfileID,
		arg.AnalyteID,
		arg.Content,
		arg.ResultCount,
	)
	return err
}
