// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analytes.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAnalyte = `-- name: CreateAnalyte :one
INSERT INTO analytes (name, default_unit, category)
VALUES ($1, $2, $3)
RETURNING id, name, default_unit, loinc, category, created_at, specimen
`

type CreateAnalyteParams struct {
	Name        string      `json:"name"`
	DefaultUnit pgtype.Text `json:"default_unit"`
	Category    pgtype.Text `json:"category"`
}

func (q *Queries) CreateAnalyte(ctx context.Context, arg CreateAnalyteParams) (Analyte, error) {
	row := q.db.QueryRow(ctx, createAnalyte, arg.Name, arg.DefaultUnit, arg.Category)
	var i Analyte
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DefaultUnit,
		&i.Loinc,
		&i.Category,
		&i.CreatedAt,
		&i.Specimen,
	)
	return i, err
}

const getAliasByRawName = `-- name: GetAliasByRawName :one
SELECT a.id, a.name, a.default_unit, a.loinc, a.category, a.created_at, a.specimen FROM analytes a
JOIN analyte_aliases al ON al.analyte_id = a.id
WHERE lower(btrim(al.raw_name)) = lower(btrim($1))
LIMIT 1
`

func (q *Queries) GetAliasByRawName(ctx context.Context, btrim string) (Analyte, error) {
	row := q.db.QueryRow(ctx, getAliasByRawName, btrim)
	var i Analyte
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DefaultUnit,
		&i.Loinc,
		&i.Category,
		&i.CreatedAt,
		&i.Specimen,
	)
	return i, err
}

const getAnalyte = `-- name: GetAnalyte :one
SELECT id, name, default_unit, loinc, category, created_at, specimen FROM analytes
WHERE id = $1
`

func (q *Queries) GetAnalyte(ctx context.Context, id uuid.UUID) (Analyte, error) {
	row := q.db.QueryRow(ctx, getAnalyte, id)
	var i Analyte
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DefaultUnit,
		&i.Loinc,
		&i.Category,
		&i.CreatedAt,
		&i.Specimen,
	)
	return i, err
}

const getAnalyteByName = `-- name: GetAnalyteByName :one
SELECT id, name, default_unit, loinc, category, created_at, specimen FROM analytes
WHERE lower(btrim(name)) = lower(btrim($1))
LIMIT 1
`

func (q *Queries) GetAnalyteByName(ctx context.Context, btrim string) (Analyte, error) {
	row := q.db.QueryRow(ctx, getAnalyteByName, btrim)
	var i Analyte
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DefaultUnit,
		&i.Loinc,
		&i.Category,
		&i.CreatedAt,
		&i.Specimen,
	)
	return i, err
}

const listAnalytes = `-- name: ListAnalytes :many
SELECT id, name, default_unit, loinc, category, created_at, specimen FROM analytes
ORDER BY category NULLS LAST, name
`

func (q *Queries) ListAnalytes(ctx context.Context) ([]Analyte, error) {
	rows, err := q.db.Query(ctx, listAnalytes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Analyte{}
	for rows.Next() {
		var i Analyte
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DefaultUnit,
			&i.Loinc,
			&i.Category,
			&i.CreatedAt,
			&i.Specimen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnalytesWithDataForProfile = `-- name: ListAnalytesWithDataForProfile :many
SELECT DISTINCT a.id, a.name, a.default_unit, a.loinc, a.category, a.created_at, a.specimen FROM analytes a
JOIN lab_results r ON r.analyte_id = a.id
WHERE r.profile_id = $1
ORDER BY a.category NULLS LAST, a.name
`

func (q *Queries) ListAnalytesWithDataForProfile(ctx context.Context, profileID uuid.UUID) ([]Analyte, error) {
	rows, err := q.db.Query(ctx, listAnalytesWithDataForProfile, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Analyte{}
	for rows.Next() {
		var i Analyte
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DefaultUnit,
			&i.Loinc,
			&i.Category,
			&i.CreatedAt,
			&i.Specimen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const matchAliasBySpecimen = `-- name: MatchAliasBySpecimen :one
SELECT a.id, a.name, a.default_unit, a.loinc, a.category, a.created_at, a.specimen FROM analytes a
JOIN analyte_aliases al ON al.analyte_id = a.id
WHERE lower(btrim(al.raw_name)) = lower(btrim($1))
  AND (
    ($2::bool AND a.specimen = 'urine')
    OR (NOT $2::bool AND a.specimen IS DISTINCT FROM 'urine')
  )
LIMIT 1
`

type MatchAliasBySpecimenParams struct {
	RawName   string `json:"raw_name"`
	WantUrine bool   `json:"want_urine"`
}

func (q *Queries) MatchAliasBySpecimen(ctx context.Context, arg MatchAliasBySpecimenParams) (Analyte, error) {
	row := q.db.QueryRow(ctx, matchAliasBySpecimen, arg.RawName, arg.WantUrine)
	var i Analyte
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DefaultUnit,
		&i.Loinc,
		&i.Category,
		&i.CreatedAt,
		&i.Specimen,
	)
	return i, err
}

const matchAnalyteBySpecimen = `-- name: MatchAnalyteBySpecimen :one
SELECT id, name, default_unit, loinc, category, created_at, specimen FROM analytes
WHERE lower(btrim(name)) = lower(btrim($1))
  AND (
    ($2::bool AND specimen = 'urine')
    OR (NOT $2::bool AND specimen IS DISTINCT FROM 'urine')
  )
LIMIT 1
`

type MatchAnalyteBySpecimenParams struct {
	Name      string `json:"name"`
	WantUrine bool   `json:"want_urine"`
}

func (q *Queries) MatchAnalyteBySpecimen(ctx context.Context, arg MatchAnalyteBySpecimenParams) (Analyte, error) {
	row := q.db.QueryRow(ctx, matchAnalyteBySpecimen, arg.Name, arg.WantUrine)
	var i Analyte
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DefaultUnit,
		&i.Loinc,
		&i.Category,
		&i.CreatedAt,
		&i.Specimen,
	)
	return i, err
}

const upsertAlias = `-- name: UpsertAlias :exec
INSERT INTO analyte_aliases (analyte_id, raw_name)
VALUES ($1, $2)
ON CONFLICT (raw_name) DO NOTHING
`

type UpsertAliasParams struct {
	AnalyteID uuid.UUID `json:"analyte_id"`
	RawName   string    `json:"raw_name"`
}

func (q *Queries) UpsertAlias(ctx context.Context, arg UpsertAliasParams) error {
	_, err := q.db.Exec(ctx, upsertAlias, arg.AnalyteID, arg.RawName)
	return err
}
