// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: body_measurements.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addBodyMeasurement = `-- name: AddBodyMeasurement :one
INSERT INTO body_measurements (profile_id, kind, value, measured_on, source, external_id)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (profile_id, source, external_id) DO UPDATE
  SET value = EXCLUDED.value, measured_on = EXCLUDED.measured_on
RETURNING id, profile_id, kind, value, measured_on, created_at, source, external_id
`

type AddBodyMeasurementParams struct {
	ProfileID  uuid.UUID   `json:"profile_id"`
	Kind       string      `json:"kind"`
	Value      float64     `json:"value"`
	MeasuredOn pgtype.Date `json:"measured_on"`
	Source     string      `json:"source"`
	ExternalID pgtype.Text `json:"external_id"`
}

// Upsert: a row with a real external_id re-imported from the same source updates
// in place (idempotent); manual rows (external_id NULL) never conflict, so they
// always insert.
func (q *Queries) AddBodyMeasurement(ctx context.Context, arg AddBodyMeasurementParams) (BodyMeasurement, error) {
	row := q.db.QueryRow(ctx, addBodyMeasurement,
		arg.ProfileID,
		arg.Kind,
		arg.Value,
		arg.MeasuredOn,
		arg.Source,
		arg.ExternalID,
	)
	var i BodyMeasurement
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Kind,
		&i.Value,
		&i.MeasuredOn,
		&i.CreatedAt,
		&i.Source,
		&i.ExternalID,
	)
	return i, err
}

const deleteBodyMeasurement = `-- name: DeleteBodyMeasurement :exec
DELETE FROM body_measurements
WHERE id = $1 AND profile_id = $2
`

type DeleteBodyMeasurementParams struct {
	ID        uuid.UUID `json:"id"`
	ProfileID uuid.UUID `json:"profile_id"`
}

func (q *Queries) DeleteBodyMeasurement(ctx context.Context, arg DeleteBodyMeasurementParams) error {
	_, err := q.db.Exec(ctx, deleteBodyMeasurement, arg.ID, arg.ProfileID)
	return err
}

const listBodyMeasurements = `-- name: ListBodyMeasurements :many
SELECT id, profile_id, kind, value, measured_on, created_at, source, external_id FROM body_measurements
WHERE profile_id = $1
ORDER BY measured_on DESC, created_at DESC
`

func (q *Queries) ListBodyMeasurements(ctx context.Context, profileID uuid.UUID) ([]BodyMeasurement, error) {
	rows, err := q.db.Query(ctx, listBodyMeasurements, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BodyMeasurement{}
	for rows.Next() {
		var i BodyMeasurement
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.Kind,
			&i.Value,
			&i.MeasuredOn,
			&i.CreatedAt,
			&i.Source,
			&i.ExternalID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
