// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: device_reports.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDeviceReport = `-- name: CreateDeviceReport :one
INSERT INTO lab_reports (profile_id, source, external_id, source_lab, collected_date, reported_date, status)
VALUES ($1, 'device', $2, $3, $4, $4, 'saved')
ON CONFLICT (profile_id, source, external_id) DO NOTHING
RETURNING id, profile_id, pdf_object_key, original_filename, source_lab, collected_date, reported_date, status, parse_error, parsed_draft, created_at, source, external_id
`

type CreateDeviceReportParams struct {
	ProfileID     uuid.UUID   `json:"profile_id"`
	ExternalID    pgtype.Text `json:"external_id"`
	SourceLab     pgtype.Text `json:"source_lab"`
	CollectedDate pgtype.Date `json:"collected_date"`
}

// A saved, PDF-less report for one device reading. Returns no rows when this
// reading already exists on the profile.
func (q *Queries) CreateDeviceReport(ctx context.Context, arg CreateDeviceReportParams) (LabReport, error) {
	row := q.db.QueryRow(ctx, createDeviceReport,
		arg.ProfileID,
		arg.ExternalID,
		arg.SourceLab,
		arg.CollectedDate,
	)
	var i LabReport
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.PdfObjectKey,
		&i.OriginalFilename,
		&i.SourceLab,
		&i.CollectedDate,
		&i.ReportedDate,
		&i.Status,
		&i.ParseError,
		&i.ParsedDraft,
		&i.CreatedAt,
		&i.Source,
		&i.ExternalID,
	)
	return i, err
}

const listDeviceReportsByExternalIDForUser = `-- name: ListDeviceReportsByExternalIDForUser :many
SELECT rep.id, rep.profile_id, rep.external_id
FROM lab_reports rep
JOIN profiles p ON p.id = rep.profile_id
WHERE rep.source = 'device'
  AND rep.external_id = ANY($1::text[])
  AND (
      p.owner_user_id = $2
      OR EXISTS (
          SELECT 1 FROM profile_members m
          WHERE m.profile_id = p.id AND m.user_id = $2
      )
  )
`

type ListDeviceReportsByExternalIDForUserParams struct {
	ExternalIds []string   `json:"external_ids"`
	UserID      *uuid.UUID `json:"user_id"`
}

type ListDeviceReportsByExternalIDForUserRow struct {
	ID         uuid.UUID   `json:"id"`
	ProfileID  uuid.UUID   `json:"profile_id"`
	ExternalID pgtype.Text `json:"external_id"`
}

// Device reports with any of the given external ids, on profiles the user owns
// or that are shared with them. Other users' readings are never visible.
func (q *Queries) ListDeviceReportsByExternalIDForUser(ctx context.Context, arg ListDeviceReportsByExternalIDForUserParams) ([]ListDeviceReportsByExternalIDForUserRow, error) {
	rows, err := q.db.Query(ctx, listDeviceReportsByExternalIDForUser, arg.ExternalIds, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDeviceReportsByExternalIDForUserRow{}
	for rows.Next() {
		var i ListDeviceReportsByExternalIDForUserRow
		if err := rows.Scan(&i.ID, &i.ProfileID, &i.ExternalID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
