// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: favorites.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const addFavorite = `-- name: AddFavorite :exec
INSERT INTO favorites (profile_id, analyte_id)
VALUES ($1, $2)
ON CONFLICT (profile_id, analyte_id) DO NOTHING
`

type AddFavoriteParams struct {
	ProfileID uuid.UUID `json:"profile_id"`
	AnalyteID uuid.UUID `json:"analyte_id"`
}

func (q *Queries) AddFavorite(ctx context.Context, arg AddFavoriteParams) error {
	_, err := q.db.Exec(ctx, addFavorite, arg.ProfileID, arg.AnalyteID)
	return err
}

const removeFavorite = `-- name: RemoveFavorite :exec
DELETE FROM favorites
WHERE profile_id = $1 AND analyte_id = $2
`

type RemoveFavoriteParams struct {
	ProfileID uuid.UUID `json:"profile_id"`
	AnalyteID uuid.UUID `json:"analyte_id"`
}

func (q *Queries) RemoveFavorite(ctx context.Context, arg RemoveFavoriteParams) error {
	_, err := q.db.Exec(ctx, removeFavorite, arg.ProfileID, arg.AnalyteID)
	return err
}
