// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Analyte struct {
	ID          uuid.UUID          `json:"id"`
	Name        string             `json:"name"`
	DefaultUnit pgtype.Text        `json:"default_unit"`
	Loinc       pgtype.Text        `json:"loinc"`
	Category    pgtype.Text        `json:"category"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Specimens   []string           `json:"specimens"`
}

type AnalyteAlias struct {
	ID        uuid.UUID          `json:"id"`
	AnalyteID uuid.UUID          `json:"analyte_id"`
	RawName   string             `json:"raw_name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type LabReport struct {
	ID               uuid.UUID          `json:"id"`
	ProfileID        uuid.UUID          `json:"profile_id"`
	PdfObjectKey     string             `json:"pdf_object_key"`
	OriginalFilename pgtype.Text        `json:"original_filename"`
	SourceLab        pgtype.Text        `json:"source_lab"`
	CollectedDate    pgtype.Date        `json:"collected_date"`
	ReportedDate     pgtype.Date        `json:"reported_date"`
	Status           string             `json:"status"`
	ParseError       pgtype.Text        `json:"parse_error"`
	ParsedDraft      []byte             `json:"parsed_draft"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type LabResult struct {
	ID            uuid.UUID          `json:"id"`
	ReportID      uuid.UUID          `json:"report_id"`
	ProfileID     uuid.UUID          `json:"profile_id"`
	AnalyteID     uuid.UUID          `json:"analyte_id"`
	RawTestName   string             `json:"raw_test_name"`
	ValueText     pgtype.Text        `json:"value_text"`
	ValueNumeric  pgtype.Float8      `json:"value_numeric"`
	Unit          pgtype.Text        `json:"unit"`
	ReferenceLow  pgtype.Float8      `json:"reference_low"`
	ReferenceHigh pgtype.Float8      `json:"reference_high"`
	ReferenceText pgtype.Text        `json:"reference_text"`
	ObservedDate  pgtype.Date        `json:"observed_date"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Profile struct {
	ID          uuid.UUID          `json:"id"`
	Name        string             `json:"name"`
	DateOfBirth pgtype.Date        `json:"date_of_birth"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}
