// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profile_members.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addProfileMember = `-- name: AddProfileMember :exec
INSERT INTO profile_members (profile_id, user_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (profile_id, user_id) DO UPDATE SET role = EXCLUDED.role
`

type AddProfileMemberParams struct {
	ProfileID uuid.UUID `json:"profile_id"`
	UserID    uuid.UUID `json:"user_id"`
	Role      string    `json:"role"`
}

func (q *Queries) AddProfileMember(ctx context.Context, arg AddProfileMemberParams) error {
	_, err := q.db.Exec(ctx, addProfileMember, arg.ProfileID, arg.UserID, arg.Role)
	return err
}

const listProfileMembers = `-- name: ListProfileMembers :many
SELECT m.profile_id, m.user_id, m.role, m.created_at,
       u.email AS email, u.name AS name, u.oidc_sub AS oidc_sub
FROM profile_members m
JOIN users u ON u.id = m.user_id
WHERE m.profile_id = $1
ORDER BY u.email NULLS LAST, u.oidc_sub
`

type ListProfileMembersRow struct {
	ProfileID uuid.UUID          `json:"profile_id"`
	UserID    uuid.UUID          `json:"user_id"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Email     pgtype.Text        `json:"email"`
	Name      pgtype.Text        `json:"name"`
	OidcSub   string             `json:"oidc_sub"`
}

func (q *Queries) ListProfileMembers(ctx context.Context, profileID uuid.UUID) ([]ListProfileMembersRow, error) {
	rows, err := q.db.Query(ctx, listProfileMembers, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProfileMembersRow{}
	for rows.Next() {
		var i ListProfileMembersRow
		if err := rows.Scan(
			&i.ProfileID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.Email,
			&i.Name,
			&i.OidcSub,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeProfileMember = `-- name: RemoveProfileMember :exec
DELETE FROM profile_members WHERE profile_id = $1 AND user_id = $2
`

type RemoveProfileMemberParams struct {
	ProfileID uuid.UUID `json:"profile_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) RemoveProfileMember(ctx context.Context, arg RemoveProfileMemberParams) error {
	_, err := q.db.Exec(ctx, removeProfileMember, arg.ProfileID, arg.UserID)
	return err
}
