// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddFavorite(ctx context.Context, arg AddFavoriteParams) error
	CreateAnalyte(ctx context.Context, arg CreateAnalyteParams) (Analyte, error)
	CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error)
	CreateReport(ctx context.Context, arg CreateReportParams) (LabReport, error)
	CreateResult(ctx context.Context, arg CreateResultParams) (LabResult, error)
	DeleteProfile(ctx context.Context, id uuid.UUID) error
	DeleteReport(ctx context.Context, id uuid.UUID) error
	DeleteResult(ctx context.Context, id uuid.UUID) error
	DeleteResultsForReport(ctx context.Context, reportID uuid.UUID) error
	GetAliasByRawName(ctx context.Context, btrim string) (Analyte, error)
	GetAnalysis(ctx context.Context, arg GetAnalysisParams) (AnalyteAnalysis, error)
	GetAnalyte(ctx context.Context, id uuid.UUID) (Analyte, error)
	GetAnalyteByName(ctx context.Context, btrim string) (Analyte, error)
	GetProfile(ctx context.Context, id uuid.UUID) (Profile, error)
	GetReport(ctx context.Context, id uuid.UUID) (LabReport, error)
	ListAnalytes(ctx context.Context) ([]Analyte, error)
	ListAnalytesWithDataForProfile(ctx context.Context, profileID uuid.UUID) ([]Analyte, error)
	ListLatestResultsForProfile(ctx context.Context, profileID uuid.UUID) ([]ListLatestResultsForProfileRow, error)
	ListProfiles(ctx context.Context) ([]Profile, error)
	ListReportsForProfile(ctx context.Context, profileID uuid.UUID) ([]LabReport, error)
	ListResultsForProfile(ctx context.Context, profileID uuid.UUID) ([]ListResultsForProfileRow, error)
	ListResultsForProfileAnalyte(ctx context.Context, arg ListResultsForProfileAnalyteParams) ([]ListResultsForProfileAnalyteRow, error)
	MatchAliasBySpecimen(ctx context.Context, arg MatchAliasBySpecimenParams) (Analyte, error)
	MatchAnalyteBySpecimen(ctx context.Context, arg MatchAnalyteBySpecimenParams) (Analyte, error)
	RemoveFavorite(ctx context.Context, arg RemoveFavoriteParams) error
	ResultStatsForProfileAnalyte(ctx context.Context, arg ResultStatsForProfileAnalyteParams) (ResultStatsForProfileAnalyteRow, error)
	SetReportError(ctx context.Context, arg SetReportErrorParams) error
	SetReportParsed(ctx context.Context, arg SetReportParsedParams) error
	SetReportParsing(ctx context.Context, id uuid.UUID) error
	SetReportSaved(ctx context.Context, arg SetReportSavedParams) error
	UpdateResult(ctx context.Context, arg UpdateResultParams) error
	UpsertAlias(ctx context.Context, arg UpsertAliasParams) error
	UpsertAnalysis(ctx context.Context, arg UpsertAnalysisParams) error
}

var _ Querier = (*Queries)(nil)
