// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createReport = `-- name: CreateReport :one
INSERT INTO lab_reports (profile_id, pdf_object_key, original_filename, status)
VALUES ($1, $2, $3, 'parsing')
RETURNING id, profile_id, pdf_object_key, original_filename, source_lab, collected_date, reported_date, status, parse_error, parsed_draft, created_at
`

type CreateReportParams struct {
	ProfileID        uuid.UUID   `json:"profile_id"`
	PdfObjectKey     string      `json:"pdf_object_key"`
	OriginalFilename pgtype.Text `json:"original_filename"`
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (LabReport, error) {
	row := q.db.QueryRow(ctx, createReport, arg.ProfileID, arg.PdfObjectKey, arg.OriginalFilename)
	var i LabReport
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.PdfObjectKey,
		&i.OriginalFilename,
		&i.SourceLab,
		&i.CollectedDate,
		&i.ReportedDate,
		&i.Status,
		&i.ParseError,
		&i.ParsedDraft,
		&i.CreatedAt,
	)
	return i, err
}

const getReport = `-- name: GetReport :one
SELECT id, profile_id, pdf_object_key, original_filename, source_lab, collected_date, reported_date, status, parse_error, parsed_draft, created_at FROM lab_reports
WHERE id = $1
`

func (q *Queries) GetReport(ctx context.Context, id uuid.UUID) (LabReport, error) {
	row := q.db.QueryRow(ctx, getReport, id)
	var i LabReport
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.PdfObjectKey,
		&i.OriginalFilename,
		&i.SourceLab,
		&i.CollectedDate,
		&i.ReportedDate,
		&i.Status,
		&i.ParseError,
		&i.ParsedDraft,
		&i.CreatedAt,
	)
	return i, err
}

const listReportsForProfile = `-- name: ListReportsForProfile :many
SELECT id, profile_id, pdf_object_key, original_filename, source_lab, collected_date, reported_date, status, parse_error, parsed_draft, created_at FROM lab_reports
WHERE profile_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListReportsForProfile(ctx context.Context, profileID uuid.UUID) ([]LabReport, error) {
	rows, err := q.db.Query(ctx, listReportsForProfile, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LabReport{}
	for rows.Next() {
		var i LabReport
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.PdfObjectKey,
			&i.OriginalFilename,
			&i.SourceLab,
			&i.CollectedDate,
			&i.ReportedDate,
			&i.Status,
			&i.ParseError,
			&i.ParsedDraft,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setReportError = `-- name: SetReportError :exec
UPDATE lab_reports
SET status = 'error',
    parse_error = $2
WHERE id = $1
`

type SetReportErrorParams struct {
	ID         uuid.UUID   `json:"id"`
	ParseError pgtype.Text `json:"parse_error"`
}

func (q *Queries) SetReportError(ctx context.Context, arg SetReportErrorParams) error {
	_, err := q.db.Exec(ctx, setReportError, arg.ID, arg.ParseError)
	return err
}

const setReportParsed = `-- name: SetReportParsed :exec
UPDATE lab_reports
SET status = 'parsed',
    parsed_draft = $2,
    source_lab = $3,
    collected_date = $4,
    reported_date = $5
WHERE id = $1
`

type SetReportParsedParams struct {
	ID            uuid.UUID   `json:"id"`
	ParsedDraft   []byte      `json:"parsed_draft"`
	SourceLab     pgtype.Text `json:"source_lab"`
	CollectedDate pgtype.Date `json:"collected_date"`
	ReportedDate  pgtype.Date `json:"reported_date"`
}

func (q *Queries) SetReportParsed(ctx context.Context, arg SetReportParsedParams) error {
	_, err := q.db.Exec(ctx, setReportParsed,
		arg.ID,
		arg.ParsedDraft,
		arg.SourceLab,
		arg.CollectedDate,
		arg.ReportedDate,
	)
	return err
}

const setReportSaved = `-- name: SetReportSaved :exec
UPDATE lab_reports
SET status = 'saved',
    source_lab = $2,
    collected_date = $3,
    reported_date = $4
WHERE id = $1
`

type SetReportSavedParams struct {
	ID            uuid.UUID   `json:"id"`
	SourceLab     pgtype.Text `json:"source_lab"`
	CollectedDate pgtype.Date `json:"collected_date"`
	ReportedDate  pgtype.Date `json:"reported_date"`
}

func (q *Queries) SetReportSaved(ctx context.Context, arg SetReportSavedParams) error {
	_, err := q.db.Exec(ctx, setReportSaved,
		arg.ID,
		arg.SourceLab,
		arg.CollectedDate,
		arg.ReportedDate,
	)
	return err
}
