// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getUser = `-- name: GetUser :one
SELECT id, oidc_sub, email, name, created_at, last_seen_at FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OidcSub,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, oidc_sub, email, name, created_at, last_seen_at FROM users WHERE lower(email) = lower($1)
`

// Used when sharing a profile by email. Case-insensitive; the user must have
// signed in at least once (so a row exists) to be a share target.
func (q *Queries) GetUserByEmail(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OidcSub,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const getUserBySub = `-- name: GetUserBySub :one
SELECT id, oidc_sub, email, name, created_at, last_seen_at FROM users WHERE oidc_sub = $1
`

func (q *Queries) GetUserBySub(ctx context.Context, oidcSub string) (User, error) {
	row := q.db.QueryRow(ctx, getUserBySub, oidcSub)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OidcSub,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (oidc_sub, email, name, last_seen_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (oidc_sub) DO UPDATE
SET email = EXCLUDED.email,
    name = EXCLUDED.name,
    last_seen_at = now()
RETURNING id, oidc_sub, email, name, created_at, last_seen_at
`

type UpsertUserParams struct {
	OidcSub string      `json:"oidc_sub"`
	Email   pgtype.Text `json:"email"`
	Name    pgtype.Text `json:"name"`
}

// Called on every authenticated request from the JWT's sub/email/name. The sub
// is the stable identity; email/name are refreshed and last_seen_at bumped.
func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser, arg.OidcSub, arg.Email, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OidcSub,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}
