// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getUser = `-- name: GetUser :one
SELECT id, oidc_sub, email, name, created_at, last_seen_at FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OidcSub,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, oidc_sub, email, name, created_at, last_seen_at FROM users WHERE lower(email) = lower($1)
`

// Used when sharing a profile by email. Case-insensitive; the user must have
// signed in at least once (so a row exists) to be a share target.
func (q *Queries) GetUserByEmail(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OidcSub,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const getUserBySub = `-- name: GetUserBySub :one
SELECT id, oidc_sub, email, name, created_at, last_seen_at FROM users WHERE oidc_sub = $1
`

func (q *Queries) GetUserBySub(ctx context.Context, oidcSub string) (User, error) {
	row := q.db.QueryRow(ctx, getUserBySub, oidcSub)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OidcSub,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const listUsersWithProfileCounts = `-- name: ListUsersWithProfileCounts :many
SELECT u.id, u.email, u.name, u.oidc_sub, u.created_at, u.last_seen_at,
       (SELECT count(*) FROM profiles p WHERE p.owner_user_id = u.id)::int AS owned_count,
       (SELECT count(*) FROM profile_members m WHERE m.user_id = u.id)::int AS shared_count
FROM users u
ORDER BY u.created_at
`

type ListUsersWithProfileCountsRow struct {
	ID          uuid.UUID          `json:"id"`
	Email       pgtype.Text        `json:"email"`
	Name        pgtype.Text        `json:"name"`
	OidcSub     string             `json:"oidc_sub"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	LastSeenAt  pgtype.Timestamptz `json:"last_seen_at"`
	OwnedCount  int32              `json:"owned_count"`
	SharedCount int32              `json:"shared_count"`
}

// Admin view: every user with how many profiles they own and how many are
// shared with them.
func (q *Queries) ListUsersWithProfileCounts(ctx context.Context) ([]ListUsersWithProfileCountsRow, error) {
	rows, err := q.db.Query(ctx, listUsersWithProfileCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersWithProfileCountsRow{}
	for rows.Next() {
		var i ListUsersWithProfileCountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.OidcSub,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.OwnedCount,
			&i.SharedCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (oidc_sub, email, name, last_seen_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (oidc_sub) DO UPDATE
SET email = EXCLUDED.email,
    name = EXCLUDED.name,
    last_seen_at = now()
RETURNING id, oidc_sub, email, name, created_at, last_seen_at
`

type UpsertUserParams struct {
	OidcSub string      `json:"oidc_sub"`
	Email   pgtype.Text `json:"email"`
	Name    pgtype.Text `json:"name"`
}

// Called on every authenticated request from the JWT's sub/email/name. The sub
// is the stable identity; email/name are refreshed and last_seen_at bumped.
func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser, arg.OidcSub, arg.Email, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OidcSub,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}
