-- Common canonical analytes. Units are typical US conventional units.
INSERT INTO analytes (name, default_unit, category) VALUES
    ('Glucose',                  'mg/dL',  'Metabolic'),
    ('Hemoglobin A1c',           '%',      'Metabolic'),
    ('BUN',                      'mg/dL',  'Metabolic'),
    ('Creatinine',               'mg/dL',  'Metabolic'),
    ('eGFR',                     'mL/min', 'Metabolic'),
    ('Sodium',                   'mmol/L', 'Electrolytes'),
    ('Potassium',                'mmol/L', 'Electrolytes'),
    ('Chloride',                 'mmol/L', 'Electrolytes'),
    ('Carbon Dioxide',           'mmol/L', 'Electrolytes'),
    ('Calcium',                  'mg/dL',  'Electrolytes'),
    ('Total Cholesterol',        'mg/dL',  'Lipids'),
    ('HDL Cholesterol',          'mg/dL',  'Lipids'),
    ('LDL Cholesterol',          'mg/dL',  'Lipids'),
    ('Triglycerides',            'mg/dL',  'Lipids'),
    ('TSH',                      'mIU/L',  'Thyroid'),
    ('Free T4',                  'ng/dL',  'Thyroid'),
    ('Vitamin D, 25-Hydroxy',    'ng/mL',  'Vitamins'),
    ('Vitamin B12',              'pg/mL',  'Vitamins'),
    ('Ferritin',                 'ng/mL',  'Hematology'),
    ('WBC',                      'x10E3/uL','Hematology'),
    ('RBC',                      'x10E6/uL','Hematology'),
    ('Hemoglobin',               'g/dL',   'Hematology'),
    ('Hematocrit',               '%',      'Hematology'),
    ('Platelets',                'x10E3/uL','Hematology'),
    ('ALT',                      'U/L',    'Liver'),
    ('AST',                      'U/L',    'Liver'),
    ('Alkaline Phosphatase',     'U/L',    'Liver'),
    ('Total Bilirubin',          'mg/dL',  'Liver'),
    ('Albumin',                  'g/dL',   'Liver'),
    ('Total Protein',            'g/dL',   'Liver')
ON CONFLICT (name) DO NOTHING;

-- Aliases: common raw names different labs print, mapped to the canonical analyte.
INSERT INTO analyte_aliases (analyte_id, raw_name)
SELECT a.id, v.raw_name
FROM (VALUES
    ('Glucose',              'Glucose, Serum'),
    ('Glucose',              'Glucose, Fasting'),
    ('Glucose',              'Glucose, Plasma'),
    ('Hemoglobin A1c',       'Hemoglobin A1c'),
    ('Hemoglobin A1c',       'HbA1c'),
    ('Hemoglobin A1c',       'A1c'),
    ('Hemoglobin A1c',       'Hgb A1C'),
    ('BUN',                  'Urea Nitrogen (BUN)'),
    ('BUN',                  'Blood Urea Nitrogen'),
    ('Creatinine',           'Creatinine, Serum'),
    ('eGFR',                 'eGFR'),
    ('eGFR',                 'eGFR (CKD-EPI)'),
    ('Sodium',               'Sodium, Serum'),
    ('Potassium',            'Potassium, Serum'),
    ('Chloride',             'Chloride, Serum'),
    ('Carbon Dioxide',       'CO2'),
    ('Carbon Dioxide',       'Carbon Dioxide, Total'),
    ('Calcium',              'Calcium, Serum'),
    ('Total Cholesterol',    'Cholesterol, Total'),
    ('Total Cholesterol',    'Cholesterol'),
    ('HDL Cholesterol',      'HDL'),
    ('HDL Cholesterol',      'HDL-C'),
    ('LDL Cholesterol',      'LDL'),
    ('LDL Cholesterol',      'LDL-C (Calc)'),
    ('LDL Cholesterol',      'LDL Cholesterol Calc'),
    ('Triglycerides',        'Triglyceride'),
    ('TSH',                  'TSH, 3rd Generation'),
    ('TSH',                  'Thyroid Stimulating Hormone'),
    ('Free T4',              'T4, Free'),
    ('Free T4',              'Free Thyroxine'),
    ('Vitamin D, 25-Hydroxy','Vitamin D, 25-OH, Total'),
    ('Vitamin D, 25-Hydroxy','25-Hydroxyvitamin D'),
    ('Vitamin B12',          'Vitamin B12'),
    ('Vitamin B12',          'B12'),
    ('Ferritin',             'Ferritin, Serum'),
    ('WBC',                  'White Blood Cell Count'),
    ('WBC',                  'Leukocytes'),
    ('RBC',                  'Red Blood Cell Count'),
    ('RBC',                  'Erythrocytes'),
    ('Hemoglobin',           'Hgb'),
    ('Hematocrit',           'Hct'),
    ('Platelets',            'Platelet Count'),
    ('ALT',                  'ALT (SGPT)'),
    ('ALT',                  'Alanine Aminotransferase'),
    ('AST',                  'AST (SGOT)'),
    ('AST',                  'Aspartate Aminotransferase'),
    ('Alkaline Phosphatase', 'Alk Phos'),
    ('Total Bilirubin',      'Bilirubin, Total'),
    ('Albumin',              'Albumin, Serum'),
    ('Total Protein',        'Protein, Total')
) AS v(analyte_name, raw_name)
JOIN analytes a ON a.name = v.analyte_name
ON CONFLICT (raw_name) DO NOTHING;
